import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/organisms/Header'
import 'mapbox-gl/dist/mapbox-gl.css';
import Footer from '@/components/organisms/Footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es"> 
      <body className={inter.className}>
     {/*  <Nav/> */}
        <Header/> 
        {children}
        <Footer/> 
      </body>
    </html>
  )
}
